name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run Unit Test
        run: go test -cover ./...

      - name: Run Unit Tests and Generate Coverage Profile
        run: go test -coverprofile=coverage.out ./...

      - name: Generate HTML Coverage Report
        # This step creates an HTML report from the coverage.out file.
        # You can then open this HTML file in your browser.
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
              name: go-coverage-report
              path: coverage.html
              # Optional: Set retention days for the artifact (e.g., 5 days)
              retention-days: 5